### ISSUE TITLE
Implement line colors via Masking

### ISSUE THREAD

**Issue by CasperStaahl** [P6-AAU-23/real-time-whiteboard-app#29]

**Comment by TerranAster** [comment]
Friendly reminder that when it asks for a file path, it is in the EMULATOR, not on your computer :)

**Comment by TerranAster** [comment]
Thomas continues w expanding on full project, Aster begins a test project

**Comment by TerranAster** [comment]
Thomas got test to work, Aster abandons test project to continue on main project with Thomas (now with better knowledge of android development)
